# https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
# https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action#creating-an-action-metadata-file
name: Deploy to AWS S3

description: Deploy a static website via AWS S3

runs:
  using: node20
  main: main.js
