# Composite Action
# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

name: Get & Cache Dependencies

description: Get dependencies via npm and cache them

inputs:
  caching:
    description: Enable or disable dependency caching
    required: false
    default: 'true'

outputs:
  used-cache:
    description: Indicates whether cache was used
    value: ${{ steps.install.outputs.cache }}
runs:
  using: composite
  steps:
    - name: Cache dependencies
      # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
      if: inputs.caching == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      id: install
      shell: bash  # Choose shell for running the command
      if: >
        steps.cache.outputs.cache-hit != 'true'
        || inputs.caching != 'true'
      run: |
        npm ci
        echo "cache=${{ inputs.caching }}" >> $GITHUB_OUTPUT
