# Section 9: Building & Using Custom Actions

# Why?
# - simplify workflows
# - no existing community action
# - contribute back to the community

# https://docs.github.com/en/actions/creating-actions/about-custom-actions#types-of-actions
# Types of Custom Actions
# 1. JavaScript Actions
# 2. Docker Actions
# 3. Composite Actions

# Java Script Actions
# - Execute a JavaScript file
# - Use JavaScript (NodeJS) + any packages of your choice

# Docker Actions
# - Create a Dockerfile with your required configuration
# - Perform any task(s) of your choice with any language

# Composite Actions
# - Combine multiple Workflow Steps in one single Action
# - Combine run (commands) and uses (actions)
# - Allows for reusing shared Steps (without extra skills)

name: Deployment
on:
  push:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install and cache dependencies
        id: cache-dependencies
        # Using actions in my repository
        # uses: my-github-username/my-action-repository
        # Using actions in the same repository
        uses: ./.github/actions/cached-dependencies  # Github automatically looks for the `actions.yml` file
        with:
          caching: 'false'
      - name: Output information
        run: echo "Cache used? ${{ steps.cache-dependencies.outputs.used-cache }}"
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install and cache dependencies
        # Using actions in my repository
        # uses: my-github-username/my-action-repository
        # Using actions in the same repository
        uses: ./.github/actions/cached-dependencies  # Github automatically looks for the `actions.yml` file
      - name: Test code
        id: run-tests
        run: npm run test
      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install and cache dependencies
        # Using actions in my repository
        # uses: my-github-username/my-action-repository
        # Using actions in the same repository
        uses: ./.github/actions/cached-dependencies  # Github automatically looks for the `actions.yml` file
      - name: Build website
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Get build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
          path: ./dist
      - name: Output contents
        run: ls
      - name: Deploy site
        run: echo "Deploying..."
  information:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Custom JavaScript action
        # When using action from same repository, include checkout step, not required for actions from another github repository
        # Error: Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under '/home/runner/work/training-github-actions-09-custom-actions/training-github-actions-09-custom-actions/.github/actions/deploy-s3-javascript'. Did you forget to run actions/checkout before running your local action?
        uses: ./.github/actions/deploy-s3-javascript
